;; Crew Optimization Scheduler
(define-constant contract-owner tx-sender)
(define-constant err-owner-only (err u100))
(define-constant err-not-found (err u101))
(define-constant err-unauthorized (err u102))
(define-constant err-invalid-status (err u103))
(define-constant err-fatigue-violation (err u104))
(define-constant status-available u1)
(define-constant status-scheduled u2)
(define-constant status-resting u4)
(define-constant flight-scheduled u1)
(define-constant flight-completed u3)
(define-data-var crew-id-nonce uint u0)
(define-data-var flight-id-nonce uint u0)
(define-data-var schedule-id-nonce uint u0)
(define-data-var total-crews uint u0)
(define-data-var total-flights uint u0)
(define-map crew-members { crew-id: uint } { crew-member: principal, name: (string-ascii 100), position: (string-ascii 50), certification: (string-ascii 100), status: uint, total-hours: uint, rest-hours: uint, last-duty-end: uint, base-location: (string-ascii 50) })
(define-map flights { flight-id: uint } { flight-number: (string-ascii 20), origin: (string-ascii 50), destination: (string-ascii 50), departure-time: uint, duration: uint, status: uint, crew-required: uint, created-at: uint })
(define-map schedules { schedule-id: uint } { flight-id: uint, crew-id: uint, assigned-at: uint, duty-start: uint, duty-end: uint, payment-amount: uint, status: uint, paid: bool })
(define-map crew-schedules { crew-id: uint, schedule-index: uint } { schedule-id: uint })
(define-map crew-schedule-counts { crew-id: uint } { count: uint })
(define-map flight-crew-assignments { flight-id: uint, crew-index: uint } { crew-id: uint })
(define-map flight-crew-counts { flight-id: uint } { count: uint })
(define-map crew-stats { crew-id: uint } { total-flights: uint, total-hours: uint, total-earned: uint, compliance-score: uint })
(define-private (get-next-crew-id) (let ((current-id (var-get crew-id-nonce))) (var-set crew-id-nonce (+ current-id u1)) current-id))
(define-private (get-next-flight-id) (let ((current-id (var-get flight-id-nonce))) (var-set flight-id-nonce (+ current-id u1)) current-id))
(define-private (get-next-schedule-id) (let ((current-id (var-get schedule-id-nonce))) (var-set schedule-id-nonce (+ current-id u1)) current-id))
(define-public (register-crew (name (string-ascii 100)) (position (string-ascii 50)) (certification (string-ascii 100)) (base-location (string-ascii 50))) (let ((crew-id (get-next-crew-id))) (map-set crew-members { crew-id: crew-id } { crew-member: tx-sender, name: name, position: position, certification: certification, status: status-available, total-hours: u0, rest-hours: u24, last-duty-end: u0, base-location: base-location }) (map-set crew-schedule-counts { crew-id: crew-id } { count: u0 }) (map-set crew-stats { crew-id: crew-id } { total-flights: u0, total-hours: u0, total-earned: u0, compliance-score: u100 }) (var-set total-crews (+ (var-get total-crews) u1)) (ok crew-id)))
(define-public (create-flight (flight-number (string-ascii 20)) (origin (string-ascii 50)) (destination (string-ascii 50)) (departure-time uint) (duration uint) (crew-required uint)) (let ((flight-id (get-next-flight-id))) (map-set flights { flight-id: flight-id } { flight-number: flight-number, origin: origin, destination: destination, departure-time: departure-time, duration: duration, status: flight-scheduled, crew-required: crew-required, created-at: stacks-block-height }) (map-set flight-crew-counts { flight-id: flight-id } { count: u0 }) (var-set total-flights (+ (var-get total-flights) u1)) (ok flight-id)))
(define-public (assign-crew (flight-id uint) (crew-id uint) (payment-amount uint)) (let ((flight (unwrap! (map-get? flights { flight-id: flight-id }) err-not-found)) (crew (unwrap! (map-get? crew-members { crew-id: crew-id }) err-not-found)) (schedule-id (get-next-schedule-id)) (duty-duration (get duration flight)) (crew-count (unwrap! (map-get? crew-schedule-counts { crew-id: crew-id }) err-not-found)) (flight-crew-count (unwrap! (map-get? flight-crew-counts { flight-id: flight-id }) err-not-found))) (asserts! (is-eq (get status crew) status-available) err-invalid-status) (asserts! (< (get total-hours crew) u840) err-fatigue-violation) (map-set schedules { schedule-id: schedule-id } { flight-id: flight-id, crew-id: crew-id, assigned-at: stacks-block-height, duty-start: (get departure-time flight), duty-end: (+ (get departure-time flight) duty-duration), payment-amount: payment-amount, status: flight-scheduled, paid: false }) (map-set crew-schedules { crew-id: crew-id, schedule-index: (get count crew-count) } { schedule-id: schedule-id }) (map-set crew-schedule-counts { crew-id: crew-id } { count: (+ (get count crew-count) u1) }) (map-set flight-crew-assignments { flight-id: flight-id, crew-index: (get count flight-crew-count) } { crew-id: crew-id }) (map-set flight-crew-counts { flight-id: flight-id } { count: (+ (get count flight-crew-count) u1) }) (map-set crew-members { crew-id: crew-id } (merge crew { status: status-scheduled })) (ok schedule-id)))
(define-public (complete-duty (schedule-id uint)) (let ((schedule (unwrap! (map-get? schedules { schedule-id: schedule-id }) err-not-found)) (crew (unwrap! (map-get? crew-members { crew-id: (get crew-id schedule) }) err-not-found)) (stats (unwrap! (map-get? crew-stats { crew-id: (get crew-id schedule) }) err-not-found)) (payment (get payment-amount schedule)) (duty-hours (get duration (unwrap! (map-get? flights { flight-id: (get flight-id schedule) }) err-not-found)))) (asserts! (not (get paid schedule)) err-invalid-status) (try! (stx-transfer? payment tx-sender (get crew-member crew))) (map-set schedules { schedule-id: schedule-id } (merge schedule { status: flight-completed, paid: true })) (map-set crew-members { crew-id: (get crew-id schedule) } (merge crew { status: status-resting, total-hours: (+ (get total-hours crew) duty-hours), rest-hours: u0, last-duty-end: stacks-block-height })) (map-set crew-stats { crew-id: (get crew-id schedule) } (merge stats { total-flights: (+ (get total-flights stats) u1), total-hours: (+ (get total-hours stats) duty-hours), total-earned: (+ (get total-earned stats) payment) })) (ok true)))
(define-public (update-availability (crew-id uint) (new-status uint)) (let ((crew (unwrap! (map-get? crew-members { crew-id: crew-id }) err-not-found))) (asserts! (is-eq tx-sender (get crew-member crew)) err-unauthorized) (map-set crew-members { crew-id: crew-id } (merge crew { status: new-status })) (ok true)))
(define-read-only (get-crew (crew-id uint)) (map-get? crew-members { crew-id: crew-id }))
(define-read-only (get-flight (flight-id uint)) (map-get? flights { flight-id: flight-id }))
(define-read-only (get-schedule (schedule-id uint)) (map-get? schedules { schedule-id: schedule-id }))
(define-read-only (get-crew-schedule (crew-id uint) (schedule-index uint)) (map-get? crew-schedules { crew-id: crew-id, schedule-index: schedule-index }))
(define-read-only (get-crew-stats (crew-id uint)) (map-get? crew-stats { crew-id: crew-id }))
(define-read-only (get-platform-stats) { total-crews: (var-get total-crews), total-flights: (var-get total-flights) })
